// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using totally_legit_horoscopes_api.Contexts;

namespace totally_legit_horoscopes_api.Migrations
{
    [DbContext(typeof(TotallyLegitHoroscopesContext))]
    [Migration("20210609182352_SeededStarSigns")]
    partial class SeededStarSigns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("totally_legit_horoscopes_api.Models.Profession", b =>
                {
                    b.Property<long>("ProfessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProfessionId");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("totally_legit_horoscopes_api.Models.StarSign", b =>
                {
                    b.Property<long>("StarSignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("StarSignId");

                    b.ToTable("StarSigns");

                    b.HasData(
                        new
                        {
                            StarSignId = 1L,
                            EndDate = new DateTime(1, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aquarius",
                            StartDate = new DateTime(1, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StarSignId = 2L,
                            EndDate = new DateTime(1, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pisces",
                            StartDate = new DateTime(1, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StarSignId = 3L,
                            EndDate = new DateTime(1, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aries",
                            StartDate = new DateTime(1, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StarSignId = 4L,
                            EndDate = new DateTime(1, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Taurus",
                            StartDate = new DateTime(1, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StarSignId = 5L,
                            EndDate = new DateTime(1, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gemini",
                            StartDate = new DateTime(1, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StarSignId = 6L,
                            EndDate = new DateTime(1, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cancer",
                            StartDate = new DateTime(1, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StarSignId = 7L,
                            EndDate = new DateTime(1, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Leo",
                            StartDate = new DateTime(1, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StarSignId = 8L,
                            EndDate = new DateTime(1, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Virgo",
                            StartDate = new DateTime(1, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StarSignId = 9L,
                            EndDate = new DateTime(1, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Libra",
                            StartDate = new DateTime(1, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StarSignId = 10L,
                            EndDate = new DateTime(1, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Scorpius",
                            StartDate = new DateTime(1, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StarSignId = 11L,
                            EndDate = new DateTime(1, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sagiattarius",
                            StartDate = new DateTime(1, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StarSignId = 12L,
                            EndDate = new DateTime(1, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Capricornus",
                            StartDate = new DateTime(1, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("totally_legit_horoscopes_api.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Dob")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NthChild")
                        .HasColumnType("integer");

                    b.Property<long?>("ProfessionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StarSignId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("StarSignId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("totally_legit_horoscopes_api.Models.User", b =>
                {
                    b.HasOne("totally_legit_horoscopes_api.Models.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.HasOne("totally_legit_horoscopes_api.Models.StarSign", "StarSign")
                        .WithMany()
                        .HasForeignKey("StarSignId");

                    b.Navigation("Profession");

                    b.Navigation("StarSign");
                });
#pragma warning restore 612, 618
        }
    }
}
